### PR TITLE
various enhancements

### PR DESCRIPTION
**Pull request by X-Raym**
* v0.4 (2015-03-05), by X-Raym:
	# contextual os-based separator
	+ negative first selected item pos fix (consider first selected start as time = 0 if there is an item selected)
	+ no item selected => export all items on first selected track as subtitles
	+ item selected => export only selected items as subtitles

### CODE REVIEW

**Comment by X-Raym** [comment]
I have another enhancement idea but I dont know if I can modify this file so I will let your see/control/merge this pull request first, and then propose you this third enhancement.
The ideas is to replace "count selected media items" by a loop for "count selected media items on first selected track only", and store selected items in first selected track to allow export of them only.

**Comment by hedacoder** [comment]
It seems a good idea to be able to export some items only if you have some selected. I am wondering how can I test this before merging it

**Comment by X-Raym** [comment]
There is a view file button :)
https://github.com/X-Raym/REAPER-scripts/blob/patch-2/HeDa_Subtitles%20Tools/HeDa_Export%20SRT.lua

For the moment, because the export only selected file on select track work with CountSlectedItem, it doesn't really work as excepted. For the moment (v0.4) it will export notes of every selected items (which is fine), even if they are not on selected track (which is not fine). I know how to fix this.

Meanwhile, I have an other enhancement to propose you: a second user input field for file name. The fact is that exporting with track name as default is nice, but not be able to modify it is not very handy (I made a dozen of export today), if we need several version of our subtitles track (different offset for exemple), of if we want to export several item selection from the same track etc... More, we tend to name srt file based on related video file, and the subtitles track is better named "Subitles_FR" than "my_awesome_video.mp4" :P
I can work on this if you want, it will not be hard to implement.

**Comment by hedacoder** [comment]
Maybe it is a good idea to use different tracks and export all items in various tracks. Because this way we could separate actors by tracks or by anything you need. For example subtitles that are descriptive in a separated track, or impaired hearing subtitles in another track...  etc...  Then we can have some scripts that add ( and ) for those and easilly select them all to change it.. or to change formatting.. etc...Then you could export quickly a version that includes impaired hearing subtitles and another export without selecting that track to quickly create another version of the subtitles without it. 
Notes Reader should support reading text items from multiple tracks.  I think it is a good idea.

very good idea to be able to specify the name of the file too.

**Comment by X-Raym** [comment]
I thought about multiple tracks export but determine which item is next to the other across selected track, with the way reaper functions loop though item selection or items on a track, is a bit difficult to consider for the moment.

Do you work on this multiple user fields ? Or will you I do it before merging this pull request ? I can do the loop through selected item on first selected track too. :)

**Comment by X-Raym** [comment]
Multiple line note reader... That become serious :D

**Comment by hedacoder** [comment]
multiple tracks exporting should not be difficult. Try ignoring just the tracks and do for each selected items. Select all items in all selected tracks first, and then do for each selected item. 
I cannot do any more coding today so you can do it if you have time and I can merge it all later

**Comment by X-Raym** [comment]
thanks Heda, I will do it later! And yes, Multitracks exporting... we can do it :D

**Pull request closed without merging**
