### PR TITLE
v0.5

### PR DESCRIPTION
**Pull request by X-Raym**
* v0.5 (2015-03-05), by X-Raym
 	# default name is track name - thanks to spk77 for split at comma
 	# default folder is project folder
 	# if empty fields, back to default values

### CODE REVIEW

**Comment by X-Raym** [comment]
I think I just succeed the multitrack export :D this would be for a other pull request, I need to clean the code.

**Comment by hedacoder** [comment]
Still there is the negative time bug, if no items are selected. If negative time found, It should move initialtime to first item in track, or better to 00:00. easier. So it would be, it time of first item in track > initialcursor position then initialtime=0

When items are selected it moves initialtime to time of first selected item, but maybe it is not what you want. Maybe you want to export selected items but from 00:00

the filename and path project default, very good :)

**Comment by hedacoder** [comment]
multitrack already works if multiple items in multiple tracks are selected. except we will have to deal with overlapped items in time. But for now leave that responsibility to the user, to not create overlapped text items in first place.

**Comment by X-Raym** [comment]
Yes multitracks works but not as espectef, since getselectedmediaitems loop per track.
But you know what? I did a v0.6 yesterday night and... multiple tracks subtitling came alive. We can select tracks or just items, they are exported in the right order :) 
I will correct time negative bug and show you this v0.6 who took me hours of work ^^
We definitely need a multitrack note reader now :D

**Comment by X-Raym** [comment]
In fact, the bug is already corrected if I'l not wrong. I will post that in few moment :P
(Overlapping items is not a issue, all subtiles software can deal with it)

**Comment by X-Raym** [comment]
If you agree with this, I will update the next version on my account, as almost everything has change since your version, except the way the time code is set and the way the file written; it has a totally new behavior (more conditions, undo point placement, refresh, restoration, negative offset, track or items selection, the way loops and functions are intricated...) ^^ I will be able to update it more efficiency this way, if there is any feature request/bug fix to do :) I will rename the with our both names, it would be the sign of our intense collab on this! :) Are you ok with that ? :)

**Comment by hedacoder** [comment]
Sure, you have done a lot of work on it :)

**Comment by X-Raym** [comment]
Many thanks :D It wouldn't have been possible without your hard work on this too :P Cheers!

**Pull request closed without merging**
